projet_TDW/projet_TDW/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from projet_app.admin import admin_site


urlpatterns = [
    path('admin/', admin_site.urls),
    url(r'^', include('projet_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projet_TDW/projet_app/urls.py
from django.conf.urls import url
from . import views

app_name = "projet_app"

urlpatterns = [

    #those are for AJAX and forms stuff
    url(r"^select-translators$",views.TranslatorsSelect.as_view(),name="select_translator"),
    url(r"^logout",views.Logout.as_view(),name="logout"),
    url(r"^login",views.Login.as_view(),name="login"),
    url(r"^register",views.Register.as_view(),name="register"),
    url(r"^send-request",views.SendRequest.as_view(),name="send_request"),
    url(r"^translator-transactions/(?P<pk>[\d]+)/refuse$", views.RefuseOffer.as_view(), name="refuse_request"),
    url(r"treat-response//(?P<pk>[\d]+)$",views.TreatResponse.as_view(),name="treat_response"),
    url(r"profiles/(?P<slug>[\w\d-]+)/report$",views.Report.as_view(),name="report"),
    url(r"profiles/(?P<slug>[\w\d-]+)/rate$",views.RateView.as_view(),name="rate"),

    #those are for our pages
    url(r'my-profile$',views.HomeView.as_view(),name="my profile"),
    url(r'profiles/(?P<slug>[\w\d-]+)$',views.UserProfileView.as_view(),name="profile"),
    url(r'translator-recruit$',views.RecruitTranslator.as_view(),name="recruit"),
    url(r"a-propos$",views.About.as_view(),name="about"),
    url(r"translators$",views.HomeView.as_view(),name="translators"),
    url(r"translation-types$",views.HomeView.as_view(),name="types"),
    url(r"^$",views.HomeView.as_view(),name="home"),
    url(r"^translator-transactions$",views.AllTranslatorTransactions.as_view(),name="translator_transactions"),
    url(r"^translator-transactions/(?P<pk>[\d]+)$",views.TranslationRequestDetails.as_view(),name="request_details"),
    url(r"^client-transactions$",views.AllClientTransactions.as_view(),name="client_transactions"),
    url(r"^client-transactions/(?P<pk>[\d]+)/accept$",views.ClientAccept.as_view(),name="client_accept"),
    url(r"^client-transactions/(?P<pk>[\d]+)/refuse$",views.ClientRefuse.as_view(),name="client_refuse"),
    url(r"blogs$",views.Blogs.as_view(),name="blogs"),
    url(r"blog/(?P<pk>[\d]+)$",views.BlogDetail.as_view(),name="blog_detail"),
    url(r"^chart/",views.Chart.as_view(),name="chart"),
]

projet_TDW/projet_app/views.py
from django.shortcuts import render, redirect
from .models import TranslationCategory, Language, TranslatorProfile, UserProfile, TranslationRequest
from .models import ReferenceFile,TranslationOffer,TranslationResponse,Warn, Rate, Article, Notification
from .forms import AddUserForm, AddTranslatorForm,TranslationOfferForm,SendFileForm, ReportUserForm,RateForm,ChartForm
from django.views.generic import View
from django.db.models import Q
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils import timezone
import random
from django.http import JsonResponse
# Create your views here.


ALL_CATEGORIES = TranslationCategory.objects.all()
ALL_LANGUAGES = Language.objects.all()
EMPTY_USER_FORM = AddUserForm(auto_id=False)


class HomeView(View):
    def get(self, request):
        arts = sorted(Article.objects.all(), key=lambda x: random.random())
        notifs = None
        if request.user.is_authenticated:
            notifs = Notification.objects.filter( Q(user=request.user.profile)&Q(read=False)).order_by("-date")
            for notif in notifs :
                notif.read = True
                notif.save()
        try:
            print(notifs[0].text)
        except:
            pass
        return render(request, "home.html",
                      {"categories": ALL_CATEGORIES, "languages": ALL_LANGUAGES, "form": EMPTY_USER_FORM,
                       "article1":arts[0],"article2":arts[1],"article3":arts[2],"notifications":notifs})


class TranslatorsSelect(View):
    def get(self, request):
        filters = Q()
        filters &= Q(languages__name=request.GET['src_language'])
        filters2 = Q(languages__name=request.GET['dest_language'])
        filters &= Q(categories__name=request.GET['category'])

        if request.GET["sworn_in"] == "true":
            filters &= Q(is_assermented=True)

        translators = TranslatorProfile.objects.filter(filters).filter(filters2).order_by("-global_rate")

        return render(request, "_ajax_translators.html", {'translators': translators})


class Logout(View, LoginRequiredMixin):
    def get(self, request):
        logout(request)
        return redirect("projet_app:home")


class Login(View):
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if not user.profile.is_blocked:
                login(request, user)
            else:
                messages.add_message(request, messages.ERROR, 'Votre compte Translate à été blocké')
        else:
            messages.add_message(request, messages.ERROR, 'Combinaison email/mot de passe invalide')
        return redirect("projet_app:home")


class Register(View):
    def post(self, request):
        new_form = AddUserForm(request.POST)
        if new_form.is_valid():
            user = User()
            user.username = new_form.cleaned_data['email']
            user.set_password(new_form.cleaned_data['password'])
            try:
                user.save()
            except IntegrityError:
                messages.add_message(request, messages.ERROR, 'Cet utilisateur existe déja. Veuillez prendre un autre email')
                return redirect("projet_app:recruit")


            profile = UserProfile()
            profile.phone_number = new_form.cleaned_data['phone']
            profile.full_name = "{} {}".format(new_form.cleaned_data['family_name'].upper(),
                                               new_form.cleaned_data['first_name'].title())
            profile.address = new_form.cleaned_data['address']
            profile.user = user
            profile.wilaya = new_form.cleaned_data["wilaya"]
            profile.commune = new_form.cleaned_data["commune"]
            profile.save()
            login(request, user)
        else:
            err = "Veuillez corriger les informations d'enregistrement (ouvrez l'onglet d'enregistrement pour plus de détails)."
            messages.add_message(request, messages.ERROR, err)
        return redirect("projet_app:home")


class SendRequest(View):
    def post(self, request):
        family_name = request.POST.get("family_name", "")
        first_name = request.POST.get("first_name", "")
        email = request.POST.get("email", "")
        phone = request.POST.get("phone","")
        address = request.POST.get("address", "")
        translators = request.POST.get("translators", '')
        src_lang = request.POST.get("src_lang", '')
        dest_lang = request.POST.get("dest_lang", '')
        category = request.POST.get("category", '')
        notes = request.POST.get("notes", '')
        file = request.FILES.get('file_req', '')

        for i in [family_name, first_name, email, phone, address]:
            if not i:
                messages.add_message(request, messages.ERROR, 'Veuillez renseigner l\'ensemble des informations personnelles nécessaires')
                return redirect("projet_app:home")

        if src_lang == dest_lang:
            messages.add_message(request, messages.ERROR, 'Les langues source et destination ne peuvent être égales')
            return redirect("projet_app:home")

        if not file:
            messages.add_message(request, messages.ERROR, 'Veuillez envoyez un fichier SVP')
            return redirect("projet_app:home")

        elif not file.name.lower().endswith(".pdf"):
            messages.add_message(request, messages.ERROR, 'Votre fichier doit être en format PDF')
            return redirect("projet_app:home")

        if translators.strip() == "":
            messages.add_message(request, messages.ERROR, 'Veuillez choisir au moins un traducteur svp')
            return redirect("projet_app:home")

        translator_list = translators.strip().split(" ")

        try:
            for translator in translator_list:
                trans_req = TranslationRequest()
                trans_req.full_name = "{} {}".format(family_name.upper(), first_name.title())
                trans_req.email = email
                trans_req.phone_number = phone
                trans_req.address = address
                trans_req.translator = UserProfile.objects.filter(slug=translator)[0].translator_profile
                trans_req.src_language = Language.objects.filter(name=src_lang)[0]
                trans_req.dest_language = Language.objects.filter(name=dest_lang)[0]
                trans_req.category = TranslationCategory.objects.filter(name=category)[0]
                trans_req.notes = notes
                trans_req.file = file
                trans_req.requester = request.user.profile
                trans_req.save()

                makeNewNotif(trans_req.translator.user_profile,"Vous avez reçu une demande de devis de {}".format(str(trans_req.requester)))

        except Exception:
            messages.add_message(request, messages.ERROR, "Il semblerait qu'une erreur se soit produite")
        else:
            messages.add_message(request, messages.SUCCESS, 'Votre demande a été effectuée avec succès')
        return redirect("projet_app:home")

class RecruitTranslator(View):
    def get(self,request):
        return render(request,"recruit.html",{"form":AddTranslatorForm()})

    def post(self,request):
        new_form = AddTranslatorForm(request.POST,request.FILES)

        if new_form.is_valid():
            if len(new_form.cleaned_data['languages'])==1:
                messages.add_message(request, messages.ERROR,
                                     'Attention: Un traducteur doit maîtriser plus d\'une seule langue!' )
                return render(request, "recruit.html", {"form": new_form})
            user = User()
            user.username = new_form.cleaned_data['email']
            user.set_password(new_form.cleaned_data['password'])
            try:
                user.save()
            except IntegrityError:
                messages.add_message(request, messages.ERROR, 'Cet utilisateur existe déja. Veuillez prendre un autre email')
                return render(request, "recruit.html",{"form":new_form})

            profile = UserProfile()
            profile.phone_number = new_form.cleaned_data['phone']
            profile.full_name = "{} {}".format(new_form.cleaned_data['family_name'].upper(),
                                               new_form.cleaned_data['first_name'].title())
            profile.address = new_form.cleaned_data['address']
            profile.user = user
            profile.wilaya = new_form.cleaned_data["wilaya"]
            profile.commune = new_form.cleaned_data["commune"]
            profile.save()
            translator_profile = TranslatorProfile()
            translator_profile.user_profile = profile
            translator_profile.save()
            for i in new_form.cleaned_data["languages"]:
                translator_profile.languages.add(i)
            for i in new_form.cleaned_data["categories"]:
                translator_profile.categories.add(i)
            translator_profile.cv = new_form.files.get("cv",None)
            if new_form.files.get("assermented_file",None):
                translator_profile.is_assermented=True
                translator_profile.assermented_file = new_form.files.get("assermented_file",None)
            else :
                translator_profile.is_assermented= False
            for i in ['ref1','ref2','ref3']:
                if new_form.files.get(i,None):
                    file_r = ReferenceFile()
                    file_r.translator = translator_profile
                    file_r.file = new_form.files.get(i,None)
                    file_r.save()
            translator_profile.save()
            login(request, user)
            return redirect("projet_app:home")

projet_TDW/projet_app/templates/_ajax_translators.html
<div class="row">
  {% for translator in translators %}
  <div class="card col-5 mx-3 my-4" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{translator.user_profile.full_name}}</h5>
      {% if translator.is_assermented %}
      <h6 class="card-subtitle mb-2 text-muted">Traducteur assermenté</h6>
      {% endif %}
      <p class="card-text">
        {% if translator.global_rate %} Note globale :
        {{translator.global_rate}} <br> {% endif %}
        <a href="{% url 'projet_app:profile' slug=translator.user_profile.slug %}" target="_blank">Voir le profile</a>
      </p>
      <input type="checkbox" class="form-check-input translatorCheckbox" id="trans_check{{ forloop.counter0 }}"
        data="{{translator.user_profile.slug}}" value="{{translator.user_profile.slug}}" />
      <label class="form-check-label" for="trans_check{{ forloop.counter0 }}">Choisissez ce traducteur</label>
    </div>
  </div>
  {% empty %}
  <p class="m-2 text-center">
    Aucun de nos traducteurs ne répond à vos critères, veuillez nous excuser
  </p>
  {% endfor %} {% if translators %}
  <div class="col-12"></div>
  <div class="col"></div>
  <input type="text" name="translators" type="hidden" style="display: none;" />
  <input type="submit" value="Envoyer requetes" id="submit_3"
    class="btn btn-success col-10 font-weight-bold mx-2 text-center p-3" style="visibility:hidden;" />
  <div class="col"></div>
  {% endif %}
</div>

projet_TDW/projet_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="Utf-8" />
  <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.css' %}" />
  <!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>-->
  <script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/popper.js' %}"></script>

  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <script src="{% static 'js/bootstrap.js' %}"></script>

  <link rel="stylesheet" href="{% static 'css/custom/custom-home.css' %}" />

  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <header class="border border-dark m-4">
    <section class="row m-2">
      <img id="logo" src="{% static 'img/logo.png' %}" alt="logo translate" class="col-1" />
      <div class="col"></div>
      <a href="#" class="fa fa-facebook col-1 fa-2x mt-2 mr-2"></a>
      <a href="#" class="fa fa-twitter col-1 fa-2x mt-2 mr-2"></a>
      <a href="#" class="fa fa-linkedin col-1 fa-2x mt-2 mr-2"></a>
      <a href="#" class="fa fa-wordpress col-1 fa-2x mt-2 mr-2"></a>
      {% if user.is_authenticated %}
      <div class="col-1"></div>
      <a href="{% url 'projet_app:client_transactions' %}" class="fa   fa-dashboard col-1 fa-2x mt-2 mr-2"
        data-toggle="popover" data-trigger="hover" title="Tableau de bord client"></a>

      {% if user.profile.translator_profile %}
      <a href="{% url 'projet_app:translator_transactions' %}" class="fa  fa-pencil-square col-1 fa-2x mt-2 mr-2"
        data-toggle="popover" data-trigger="hover" title="Tableau de bord traducteur"></a>
      {% endif %}
      <a href="{% url 'projet_app:profile' slug=user.profile.slug %}" class="fa fa-user col-1 fa-2x mt-2 mr-2"
        data-toggle="popover" data-trigger="hover" title="Votre profil"></a>
      {% endif %}
    </section>
    <nav class="navbar navbar-expand-lg navbar-secondary bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav container-fluid">
          <li class="nav-item col-lg text-center  ">
            <a class="" href="{% url 'projet_app:home' %}">Acceuil <span class="sr-only text-primary"></span></a>
          </li>
          <li class="nav-item col-lg text-center">
            <a class="" href="#">Types de traduction <span class="sr-only text-primary"></span></a>
          </li>
          <li class="nav-item col-lg text-center">
            <a class="" href="#">Traducteurs <span class="sr-only text-primary"></span></a>
          </li>
          <li class="nav-item col-lg text-center">
            <a class="" href="{% url 'projet_app:blogs' %}">Blogs <span class="sr-only text-primary"></span></a>
          </li>
          <li class="nav-item col-lg text-center">
            <a class="" href="{% url 'projet_app:recruit'%}">Recrutement <span class="sr-only text-primary"></span></a>
          </li>
          <li class="nav-item col-lg text-center">
            <a class="" href="{% url 'projet_app:about' %}">A propos <span class="sr-only text-primary"></span></a>
          </li>
        </ul>
      </div>
    </nav>
    <div id="carouselExampleControls" class="carousel slide " data-ride="carousel" data-interval="1500">
      <div class="carousel-inner">
        <div class="carousel-item active row  justify-content-center ">
          <div class="d-flex justify-content-center">
            <img class=" w-80 h-20 d-block  " src="{% static 'img/pub3.jpg' %}" alt="First slide" />
          </div>
        </div>

        <div class="carousel-item row  justify-content-center ">
          <div class="d-flex justify-content-center">
            <img class="d-block h-20 w-80" src="{% static 'img/pub2.jpg' %}" alt="Second slide" />
          </div>
        </div>
        <div class="carousel-item row  justify-content-center ">
          <div class="d-flex justify-content-center">
            <img class="d-block h-20 w-80 img-fluid " src="{% static 'img/pub1.jpg' %}" alt="Third slide" />
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </header>
  {% block content %} {% endblock %}
  <footer class="border border-dark m-4 bg-dark">
    <ul class="row container-fluid w-100 unstyled-list mt-2">
      <li class="col-lg text-center ">
        <a class="text-white font-weight-bold" href="{% url 'projet_app:home' %}">Acceuil <span></span></a>
      </li>
      <li class=" col-lg text-center ">
        <a class=" text-white font-weight-bold" href="#">Types de traduction</a>
      </li>
      <li class="col-lg text-center ">
        <a class="text-white font-weight-bold" href="#">Traducteurs</a>
      </li>
      <li class="col-lg text-center ">
        <a class="text-white font-weight-bold" href="{% url 'projet_app:blogs' %}">Blogs</a>
      </li>
      <li class="col-lg text-center ">
        <a class="text-white font-weight-bold" href="{% url 'projet_app:recruit' %}">Recrutement</a>
      </li>
      <li class="col-lg text-center text-white font-weight-bold">
        <a class="text-white font-weight-bold" href="{% url 'projet_app:about' %}">A propos</a>
      </li>
    </ul>
  </footer>
</body>

</html>

projet_TDW/projet_app/templates/blogs.html
{% extends "base.html" %}
{% block title %} Blogs {% endblock %}
{% block content %}
{% load template_filters %}
{% for article in articles %}
<h3>{{article.title}}</h3>
<p>
    {{article.text|start}}...
</p>
<a href="{% url 'projet_app:blog_detail' pk=article.pk %}" class="btn btn-primary">Lire la suite</a>
{% endfor %}
{% endblock %}

projet_TDW/projet_app/templates/client_transactions.html
{% extends "base.html" %}
{% block title %}Vos transactions{% endblock %}
{% block content %}
{% if messages %}
{% for message in messages %}
<h3 class="text-center text-success">
    {{message}}
</h3>
{% endfor %}
{% endif %}
<div class="row">
    <hr>
    <div class="row text-center container-fluid">
        <h1 class="col container-fluid">Dashboard</h1>
    </div>
    <div class="col-2"></div>
    <div class="col-4">

        <h3 class=" text-center my-3">
            Vos devis de traduction
        </h3>


        {% for offer in offers %}
        <hr>
        <div class="card m2">
            <h5 class="card-header text-center">Offre de : {{ offer.request.translator.user_profile.full_name }}</h5>
            <div class="card-body">
                <h5 class="card-title text-center"><a
                        href="{% url 'projet_app:profile' slug=offer.request.translator.user_profile.slug %}"
                        class="text-center">Voir le profil</a></h5>
                <div class="row align-content-center">
                    <p class="col align-self-center text-center">
                        Prix en avance : {{offer.accept_price}}DA
                    </p>
                    <p class="col align-self-center text-center">
                        Prix après traduction : {{offer.after_price}}DA
                    </p>
                </div>
                {% if offer.notes %}
                <h6 class="text-center">Notes du traducteur</h6>
                <p class="text-center">{{offer.notes}}</p>
                {% endif %}
                <a href="{{ offer.request.file.url }}" download
                    class="container-fluid btn btn-primary text-center">Télécharger le
                    fichier à
                    traduire</a>
                <hr>
                <div class="row ">
                    <a href="{% url 'projet_app:client_accept' pk=offer.pk %}"
                        class="col btn btn-success mx-3">Accpeter</a>
                    <a href="{% url 'projet_app:client_refuse' pk=offer.pk %}"
                        class="col btn btn-danger mx-3">Refuser</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p class="text-center">
            Vous n'avez aucun devis de traduction en attente
        </p>
        {% endfor %}
    </div>
    <div class="col-4">
        <h3 class=" text-center my-3">
            Vos Réponses
        </h3>


        {% for response in responses %}
        <hr>
        <div class="card m2">
            <h5 class="card-header text-center">Réponse de :
                {{ response.offer.request.translator.user_profile.full_name }}</h5>
            <div class="card-body">
                <h5 class="card-title text-center"><a href="#" class="text-center">Voir le profil</a></h5>
                <div class="row align-content-center">
                    <p class="col align-self-center text-center">
                        Prix après traduction : {{response.offer.after_price}}DA
                    </p>
                </div>
                <a href="{{ response.file.url }}" download
                    class="container-fluid btn btn-primary text-center">Télécharger la réponse</a>
                <hr>
                <a href="{% url 'projet_app:treat_response' pk=response.pk %}"
                    class="btn  btn-danger container ">Marquer
                    comme traité </a>
                <p class="text-danger text-center my-3">Attention : ne pas éxecuter cette opération avant de télécharger
                    la réponse!</p>
            </div>
        </div>
        {% empty %}
        <p class="text-center">
            Vous n'avez aucune réponse pour l'instant
        </p>
        {% endfor %}
    </div>
    <div class="col-2"></div>
</div>
{% endblock %}

projet_TDW/projet_app/templates/profile.html
{% extends "base.html" %}
{% block title %}{{profile.full_name}}{% endblock %}
{% block content %}
{% load static %}
<script src="{% static 'js/custom/profile.js' %}"></script>
<div class="row">
    <div class="col-3">
    </div>
    <div class="col">
        {% if messages %}
        {% for message in messages %}
        <h3 class="text-center text-success">
            {{message}}
        </h3>
        {% endfor %}
        {% endif %}
        <h2>{{profile.full_name}}</h2>
        <p>Adresse :
            {{profile.address}}, {{profile.commune}}, {{profile.wilaya}}
        </p>
        <hr>
        {% if profile != user.profile %}
        <button class="btn btn-primary" id="warn_button">Signaler cet utilisateur</button>
        <div id="form" style="display: none;" class="p-5">
            <form action="{% url 'projet_app:report' slug=profile.slug %}" method="POST">
                {% csrf_token %}
                <p>Qu'avez vous noté au sujet de {{profile.full_name}}?</p>
                {{warn_form.warn}}
                <input type="submit" class="container-fluid btn btn-danger my-2" value="Signaler">
            </form>
        </div>
        {% endif %}
        {% if profile.translator_profile %}
        <h2>Informations du traducteur</h2>
        <p>Nombre de traductions: {{profile.translator_profile.number_of_translations}}</p>
        <p>Moyenne des notes: {{profile.translator_profile.global_rate}}</p>
        <p>Langues maîrisées : {% for language in profile.translator_profile.languages.all %} {{language }} {% endfor %}
        </p>
        <p>Catégories de traduction : {% for categ in profile.translator_profile.categories.all %} {{categ}} -
            {% endfor %}
        </p>
        <a href="{{profile.translator_profile.cv.url}}" class="btn btn-primary" download>Télécharger le CV</a>
        <p>Télécharger les références</p>
        {% for ref in profile.translator_profile.reference_files.all %}
        <a href="{{ref.file.url}}" class="btn btn-info">Rérérence {{ forloop.counter }}</a>
        {% endfor %}
        {% endif %}
        {% if can_rate %}
        <form action="{% url 'projet_app:rate' slug=profile.slug %}" method="POST">
            {% csrf_token %}
            <p>Notez ce traducteur (remarque: Si vous avez déja noté {{profile.full_name}}, votre note sera remplacée
            </p>
            {{rate_form.rate}}
            <input type="submit" class="container-fluid btn btn-success my-2" value="Noter ce traducteur">
        </form>
        {% endif %}

    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

projet_TDW/projet_app/templates/request_detail.html
{% extends "base.html" %}
{% block title %}Details{% endblock %}
{% block content %}
<div class="container-fluid row">
    <div class="col-2"></div>
    <div class="col">
        <div class="card container ">
            <h5 class="card-header text-center">Demande de: {{ request.full_name }}</h5>
            <div class="card-body">
                <ul>
                    <p class=" align-self-center">
                        Numéro de téléphone : {{request.phone_number}}
                    </p>
                    <p class=" align-self-center">
                        Adresse : {{request.address}}
                    </p>
                    <p class=" align-self-center">
                        Email : {{request.email}}
                    </p>

                </ul>
            </div>
        </div>
        <div class="m-5">
            <p>
                Langue Source : {{request.src_language}}
            </p>
            <p>
                Langue Destination : {{request.dest_language}}
            </p>
            <p>
                Catégorie : {{request.category}}
            </p>
            <a href="{{ request.file.url }}" download class="btn btn-primary ">Télécharger le fichier à
                traduire</a>
        </div>

        <div class=" card container ">
            <h5 class=" card-header text-center">Notes du client</h5>
            <div class="card-body text-center">
                {% if request.notes %}
                {{request.notes}}
                {% else %}
                Votre client n'a rien ajouté de particulier
                {% endif %}
            </div>
        </div>
        <hr>
        <h5 class="text-center my-2">Si vous voulez accepter la demande, veuillez remplir le formulaire. Sinon, <a
                href="{% url 'projet_app:refuse_request' pk=request.pk %}" class="btn btn-danger">Refusez la demande</a>
        </h5>
        <hr>
        <div>
            <form action="{% url 'projet_app:request_details' pk=request.pk %}" method="POST"
                class="  w-75 container-fluid">
                {% csrf_token %}
                <div class="row justify-content-center align-content-center">
                    <div class="col align-self-center">
                        Prix après traduction (Champ requis) :
                    </div>
                    <div class="col">
                        {{form.price}}
                    </div>
                </div>
                <div class="row">
                    <div class="col align-self-center">
                        Prix à l'avance :
                    </div>
                    <div class="col">
                        {{form.accept_price}}
                    </div>
                </div>
                <p class="text-center text-secondary my-2 w-75 container-fluid">
                    Ce prix devra être payé à l'avance par le client (Laisser ce champ vide équivaut à 0)
                </p>
                <h6 class="text-center">Si vous avez des remarques, merci de les préciser ici </h6>
                <div>
                    {{form.notes}}
                </div>
                <input type="submit" value="Accepter la demande"
                    class="btn btn-success text-center container-fluid my-2">
            </form>
        </div>


    </div>
</div>
<div class="col-2"></div>
</div>

{% endblock %}